kind: pipeline
name: opencti

steps:
- name: front
  image: nikolaik/python-nodejs:python3.8-nodejs12-alpine
  commands:
  - apk add build-base
  - cd opencti-platform/opencti-front
  - yarn install
  - yarn lint
  - yarn build

- name: api
  image: nikolaik/python-nodejs:python3.8-nodejs12-alpine
  environment:
    APP__REACTIVE: false
    GRAKN__HOSTNAME: 127.0.0.1
    ELASTICSEARCH__HOSTNAME: 127.0.0.1
  commands:
  - apk add build-base
  - cd opencti-platform/opencti-graphql
  - yarn install
  - yarn lint
  - yarn test

services:
  grakn
    image: graknlabs/grakn:1.6.2

  elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms750m -Xmx750m

  minio
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    environment:
      - MINIO_ACCESS_KEY=ChangeMe
      - MINIO_SECRET_KEY=ChangeMe
    command: server /data

