kind: pipeline
name: default

steps:
- name: build-front
  image: nikolaik/python-nodejs:python3.8-nodejs12-alpine
  commands:
  - ls -al
  - pwd
  - apk add build-base
  - cd opencti-platform/opencti-front
  - yarn install
  - yarn build
